/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as PortalIndexRouteImport } from './routes/_portal.index'
import { Route as PortalAboutRouteImport } from './routes/_portal.about'
import { Route as PortalCityAdminsRouteImport } from './routes/_portal.city-admins'
import { Route as PortalContactRouteImport } from './routes/_portal.contact'
import { Route as PortalDirectoryRouteImport } from './routes/_portal.directory'
import { Route as PortalEventsRouteImport } from './routes/_portal.events'
import { Route as PortalPublicationsRouteImport } from './routes/_portal.publications'
import { Route as PortalVacanciesRouteImport } from './routes/_portal.vacancies'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAccountsRouteImport } from './routes/admin.accounts'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as AdminBackgroundsRouteImport } from './routes/admin.backgrounds'
import { Route as AdminCityAdminsRouteImport } from './routes/admin.city-admins'
import { Route as AdminDirectoryRouteImport } from './routes/admin.directory'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin.forgot-password'
import { Route as AdminJobApplicationsRouteImport } from './routes/admin.job-applications'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminMultimediaRouteImport } from './routes/admin.multimedia'
import { Route as AdminNewsRouteImport } from './routes/admin.news'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminPortfolioRouteImport } from './routes/admin.portfolio'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminPublicationsRouteImport } from './routes/admin.publications'
import { Route as AdminRegisterRouteImport } from './routes/admin.register'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminTendersRouteImport } from './routes/admin.tenders'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminVacanciesRouteImport } from './routes/admin.vacancies'
import { Route as PasswordResetTokenRouteImport } from './routes/password-reset.$token'
import { Route as PortalDirectoryIndexRouteImport } from './routes/_portal.directory.index'
import { Route as PortalDirectoryDirectorateIdRouteImport } from './routes/_portal.directory.$directorateId'
import { Route as PortalEventsIndexRouteImport } from './routes/_portal.events.index'
import { Route as PortalEventsIdRouteImport } from './routes/_portal.events.$id'
import { Route as PortalMultimediaImagesRouteImport } from './routes/_portal.multimedia.images'
import { Route as PortalMultimediaVideosRouteImport } from './routes/_portal.multimedia.videos'
import { Route as PortalNewsIndexRouteImport } from './routes/_portal.news.index'
import { Route as PortalNewsIdRouteImport } from './routes/_portal.news.$id'
import { Route as PortalTendersIndexRouteImport } from './routes/_portal.tenders.index'
import { Route as PortalTendersIdRouteImport } from './routes/_portal.tenders.$id'
import { Route as PortalVacanciesVacancyIdRouteImport } from './routes/_portal.vacancies.$vacancyId'
import { Route as PortalMultimediaImagesIndexRouteImport } from './routes/_portal.multimedia.images.index'
import { Route as PortalMultimediaImagesIdRouteImport } from './routes/_portal.multimedia.images.$id'
import { Route as PortalMultimediaVideosIndexRouteImport } from './routes/_portal.multimedia.videos.index'
import { Route as PortalMultimediaVideosIdRouteImport } from './routes/_portal.multimedia.videos.$id'
import { Route as PortalVacanciesVacancyIdApplyRouteImport } from './routes/_portal.vacancies.$vacancyId.apply'

const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAboutRoute = PortalAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCityAdminsRoute = PortalCityAdminsRouteImport.update({
  id: '/city-admins',
  path: '/city-admins',
  getParentRoute: () => PortalRoute,
} as any)
const PortalContactRoute = PortalContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDirectoryRoute = PortalDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEventsRoute = PortalEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPublicationsRoute = PortalPublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => PortalRoute,
} as any)
const PortalVacanciesRoute = PortalVacanciesRouteImport.update({
  id: '/vacancies',
  path: '/vacancies',
  getParentRoute: () => PortalRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/admin/accounts',
  path: '/admin/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/admin/activity',
  path: '/admin/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBackgroundsRoute = AdminBackgroundsRouteImport.update({
  id: '/admin/backgrounds',
  path: '/admin/backgrounds',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCityAdminsRoute = AdminCityAdminsRouteImport.update({
  id: '/admin/city-admins',
  path: '/admin/city-admins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDirectoryRoute = AdminDirectoryRouteImport.update({
  id: '/admin/directory',
  path: '/admin/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/admin/feedback',
  path: '/admin/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/admin/forgot-password',
  path: '/admin/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobApplicationsRoute = AdminJobApplicationsRouteImport.update({
  id: '/admin/job-applications',
  path: '/admin/job-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/admin/messages',
  path: '/admin/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMultimediaRoute = AdminMultimediaRouteImport.update({
  id: '/admin/multimedia',
  path: '/admin/multimedia',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/admin/news',
  path: '/admin/news',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPortfolioRoute = AdminPortfolioRouteImport.update({
  id: '/admin/portfolio',
  path: '/admin/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPublicationsRoute = AdminPublicationsRouteImport.update({
  id: '/admin/publications',
  path: '/admin/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegisterRoute = AdminRegisterRouteImport.update({
  id: '/admin/register',
  path: '/admin/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTendersRoute = AdminTendersRouteImport.update({
  id: '/admin/tenders',
  path: '/admin/tenders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVacanciesRoute = AdminVacanciesRouteImport.update({
  id: '/admin/vacancies',
  path: '/admin/vacancies',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetTokenRoute = PasswordResetTokenRouteImport.update({
  id: '/password-reset/$token',
  path: '/password-reset/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalDirectoryIndexRoute = PortalDirectoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalDirectoryRoute,
} as any)
const PortalDirectoryDirectorateIdRoute =
  PortalDirectoryDirectorateIdRouteImport.update({
    id: '/$directorateId',
    path: '/$directorateId',
    getParentRoute: () => PortalDirectoryRoute,
  } as any)
const PortalEventsIndexRoute = PortalEventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalEventsRoute,
} as any)
const PortalEventsIdRoute = PortalEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortalEventsRoute,
} as any)
const PortalMultimediaImagesRoute = PortalMultimediaImagesRouteImport.update({
  id: '/multimedia/images',
  path: '/multimedia/images',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMultimediaVideosRoute = PortalMultimediaVideosRouteImport.update({
  id: '/multimedia/videos',
  path: '/multimedia/videos',
  getParentRoute: () => PortalRoute,
} as any)
const PortalNewsIndexRoute = PortalNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalNewsIdRoute = PortalNewsIdRouteImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTendersIndexRoute = PortalTendersIndexRouteImport.update({
  id: '/tenders/',
  path: '/tenders/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTendersIdRoute = PortalTendersIdRouteImport.update({
  id: '/tenders/$id',
  path: '/tenders/$id',
  getParentRoute: () => PortalRoute,
} as any)
const PortalVacanciesVacancyIdRoute =
  PortalVacanciesVacancyIdRouteImport.update({
    id: '/$vacancyId',
    path: '/$vacancyId',
    getParentRoute: () => PortalVacanciesRoute,
  } as any)
const PortalMultimediaImagesIndexRoute =
  PortalMultimediaImagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PortalMultimediaImagesRoute,
  } as any)
const PortalMultimediaImagesIdRoute =
  PortalMultimediaImagesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => PortalMultimediaImagesRoute,
  } as any)
const PortalMultimediaVideosIndexRoute =
  PortalMultimediaVideosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PortalMultimediaVideosRoute,
  } as any)
const PortalMultimediaVideosIdRoute =
  PortalMultimediaVideosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => PortalMultimediaVideosRoute,
  } as any)
const PortalVacanciesVacancyIdApplyRoute =
  PortalVacanciesVacancyIdApplyRouteImport.update({
    id: '/apply',
    path: '/apply',
    getParentRoute: () => PortalVacanciesVacancyIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PortalIndexRoute
  '/about': typeof PortalAboutRoute
  '/city-admins': typeof PortalCityAdminsRoute
  '/contact': typeof PortalContactRoute
  '/directory': typeof PortalDirectoryRouteWithChildren
  '/events': typeof PortalEventsRouteWithChildren
  '/publications': typeof PortalPublicationsRoute
  '/vacancies': typeof PortalVacanciesRouteWithChildren
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/backgrounds': typeof AdminBackgroundsRoute
  '/admin/city-admins': typeof AdminCityAdminsRoute
  '/admin/directory': typeof AdminDirectoryRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/job-applications': typeof AdminJobApplicationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/multimedia': typeof AdminMultimediaRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/publications': typeof AdminPublicationsRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tenders': typeof AdminTendersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vacancies': typeof AdminVacanciesRoute
  '/password-reset/$token': typeof PasswordResetTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/directory/$directorateId': typeof PortalDirectoryDirectorateIdRoute
  '/events/$id': typeof PortalEventsIdRoute
  '/multimedia/images': typeof PortalMultimediaImagesRouteWithChildren
  '/multimedia/videos': typeof PortalMultimediaVideosRouteWithChildren
  '/news/$id': typeof PortalNewsIdRoute
  '/tenders/$id': typeof PortalTendersIdRoute
  '/vacancies/$vacancyId': typeof PortalVacanciesVacancyIdRouteWithChildren
  '/directory/': typeof PortalDirectoryIndexRoute
  '/events/': typeof PortalEventsIndexRoute
  '/news/': typeof PortalNewsIndexRoute
  '/tenders/': typeof PortalTendersIndexRoute
  '/multimedia/images/$id': typeof PortalMultimediaImagesIdRoute
  '/multimedia/videos/$id': typeof PortalMultimediaVideosIdRoute
  '/vacancies/$vacancyId/apply': typeof PortalVacanciesVacancyIdApplyRoute
  '/multimedia/images/': typeof PortalMultimediaImagesIndexRoute
  '/multimedia/videos/': typeof PortalMultimediaVideosIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof PortalAboutRoute
  '/city-admins': typeof PortalCityAdminsRoute
  '/contact': typeof PortalContactRoute
  '/publications': typeof PortalPublicationsRoute
  '/vacancies': typeof PortalVacanciesRouteWithChildren
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/backgrounds': typeof AdminBackgroundsRoute
  '/admin/city-admins': typeof AdminCityAdminsRoute
  '/admin/directory': typeof AdminDirectoryRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/job-applications': typeof AdminJobApplicationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/multimedia': typeof AdminMultimediaRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/publications': typeof AdminPublicationsRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tenders': typeof AdminTendersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vacancies': typeof AdminVacanciesRoute
  '/password-reset/$token': typeof PasswordResetTokenRoute
  '/': typeof PortalIndexRoute
  '/admin': typeof AdminIndexRoute
  '/directory/$directorateId': typeof PortalDirectoryDirectorateIdRoute
  '/events/$id': typeof PortalEventsIdRoute
  '/news/$id': typeof PortalNewsIdRoute
  '/tenders/$id': typeof PortalTendersIdRoute
  '/vacancies/$vacancyId': typeof PortalVacanciesVacancyIdRouteWithChildren
  '/directory': typeof PortalDirectoryIndexRoute
  '/events': typeof PortalEventsIndexRoute
  '/news': typeof PortalNewsIndexRoute
  '/tenders': typeof PortalTendersIndexRoute
  '/multimedia/images/$id': typeof PortalMultimediaImagesIdRoute
  '/multimedia/videos/$id': typeof PortalMultimediaVideosIdRoute
  '/vacancies/$vacancyId/apply': typeof PortalVacanciesVacancyIdApplyRoute
  '/multimedia/images': typeof PortalMultimediaImagesIndexRoute
  '/multimedia/videos': typeof PortalMultimediaVideosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_portal': typeof PortalRouteWithChildren
  '/_portal/about': typeof PortalAboutRoute
  '/_portal/city-admins': typeof PortalCityAdminsRoute
  '/_portal/contact': typeof PortalContactRoute
  '/_portal/directory': typeof PortalDirectoryRouteWithChildren
  '/_portal/events': typeof PortalEventsRouteWithChildren
  '/_portal/publications': typeof PortalPublicationsRoute
  '/_portal/vacancies': typeof PortalVacanciesRouteWithChildren
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/backgrounds': typeof AdminBackgroundsRoute
  '/admin/city-admins': typeof AdminCityAdminsRoute
  '/admin/directory': typeof AdminDirectoryRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/job-applications': typeof AdminJobApplicationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/multimedia': typeof AdminMultimediaRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/publications': typeof AdminPublicationsRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tenders': typeof AdminTendersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vacancies': typeof AdminVacanciesRoute
  '/password-reset/$token': typeof PasswordResetTokenRoute
  '/_portal/': typeof PortalIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_portal/directory/$directorateId': typeof PortalDirectoryDirectorateIdRoute
  '/_portal/events/$id': typeof PortalEventsIdRoute
  '/_portal/multimedia/images': typeof PortalMultimediaImagesRouteWithChildren
  '/_portal/multimedia/videos': typeof PortalMultimediaVideosRouteWithChildren
  '/_portal/news/$id': typeof PortalNewsIdRoute
  '/_portal/tenders/$id': typeof PortalTendersIdRoute
  '/_portal/vacancies/$vacancyId': typeof PortalVacanciesVacancyIdRouteWithChildren
  '/_portal/directory/': typeof PortalDirectoryIndexRoute
  '/_portal/events/': typeof PortalEventsIndexRoute
  '/_portal/news/': typeof PortalNewsIndexRoute
  '/_portal/tenders/': typeof PortalTendersIndexRoute
  '/_portal/multimedia/images/$id': typeof PortalMultimediaImagesIdRoute
  '/_portal/multimedia/videos/$id': typeof PortalMultimediaVideosIdRoute
  '/_portal/vacancies/$vacancyId/apply': typeof PortalVacanciesVacancyIdApplyRoute
  '/_portal/multimedia/images/': typeof PortalMultimediaImagesIndexRoute
  '/_portal/multimedia/videos/': typeof PortalMultimediaVideosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/city-admins'
    | '/contact'
    | '/directory'
    | '/events'
    | '/publications'
    | '/vacancies'
    | '/admin/accounts'
    | '/admin/activity'
    | '/admin/backgrounds'
    | '/admin/city-admins'
    | '/admin/directory'
    | '/admin/events'
    | '/admin/feedback'
    | '/admin/forgot-password'
    | '/admin/job-applications'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/multimedia'
    | '/admin/news'
    | '/admin/notifications'
    | '/admin/portfolio'
    | '/admin/profile'
    | '/admin/publications'
    | '/admin/register'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/tenders'
    | '/admin/users'
    | '/admin/vacancies'
    | '/password-reset/$token'
    | '/admin/'
    | '/directory/$directorateId'
    | '/events/$id'
    | '/multimedia/images'
    | '/multimedia/videos'
    | '/news/$id'
    | '/tenders/$id'
    | '/vacancies/$vacancyId'
    | '/directory/'
    | '/events/'
    | '/news/'
    | '/tenders/'
    | '/multimedia/images/$id'
    | '/multimedia/videos/$id'
    | '/vacancies/$vacancyId/apply'
    | '/multimedia/images/'
    | '/multimedia/videos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/city-admins'
    | '/contact'
    | '/publications'
    | '/vacancies'
    | '/admin/accounts'
    | '/admin/activity'
    | '/admin/backgrounds'
    | '/admin/city-admins'
    | '/admin/directory'
    | '/admin/events'
    | '/admin/feedback'
    | '/admin/forgot-password'
    | '/admin/job-applications'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/multimedia'
    | '/admin/news'
    | '/admin/notifications'
    | '/admin/portfolio'
    | '/admin/profile'
    | '/admin/publications'
    | '/admin/register'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/tenders'
    | '/admin/users'
    | '/admin/vacancies'
    | '/password-reset/$token'
    | '/'
    | '/admin'
    | '/directory/$directorateId'
    | '/events/$id'
    | '/news/$id'
    | '/tenders/$id'
    | '/vacancies/$vacancyId'
    | '/directory'
    | '/events'
    | '/news'
    | '/tenders'
    | '/multimedia/images/$id'
    | '/multimedia/videos/$id'
    | '/vacancies/$vacancyId/apply'
    | '/multimedia/images'
    | '/multimedia/videos'
  id:
    | '__root__'
    | '/_portal'
    | '/_portal/about'
    | '/_portal/city-admins'
    | '/_portal/contact'
    | '/_portal/directory'
    | '/_portal/events'
    | '/_portal/publications'
    | '/_portal/vacancies'
    | '/admin/accounts'
    | '/admin/activity'
    | '/admin/backgrounds'
    | '/admin/city-admins'
    | '/admin/directory'
    | '/admin/events'
    | '/admin/feedback'
    | '/admin/forgot-password'
    | '/admin/job-applications'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/multimedia'
    | '/admin/news'
    | '/admin/notifications'
    | '/admin/portfolio'
    | '/admin/profile'
    | '/admin/publications'
    | '/admin/register'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/tenders'
    | '/admin/users'
    | '/admin/vacancies'
    | '/password-reset/$token'
    | '/_portal/'
    | '/admin/'
    | '/_portal/directory/$directorateId'
    | '/_portal/events/$id'
    | '/_portal/multimedia/images'
    | '/_portal/multimedia/videos'
    | '/_portal/news/$id'
    | '/_portal/tenders/$id'
    | '/_portal/vacancies/$vacancyId'
    | '/_portal/directory/'
    | '/_portal/events/'
    | '/_portal/news/'
    | '/_portal/tenders/'
    | '/_portal/multimedia/images/$id'
    | '/_portal/multimedia/videos/$id'
    | '/_portal/vacancies/$vacancyId/apply'
    | '/_portal/multimedia/images/'
    | '/_portal/multimedia/videos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PortalRoute: typeof PortalRouteWithChildren
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminActivityRoute: typeof AdminActivityRoute
  AdminBackgroundsRoute: typeof AdminBackgroundsRoute
  AdminCityAdminsRoute: typeof AdminCityAdminsRoute
  AdminDirectoryRoute: typeof AdminDirectoryRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminJobApplicationsRoute: typeof AdminJobApplicationsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminMultimediaRoute: typeof AdminMultimediaRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPortfolioRoute: typeof AdminPortfolioRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminPublicationsRoute: typeof AdminPublicationsRoute
  AdminRegisterRoute: typeof AdminRegisterRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTendersRoute: typeof AdminTendersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVacanciesRoute: typeof AdminVacanciesRoute
  PasswordResetTokenRoute: typeof PasswordResetTokenRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/': {
      id: '/_portal/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/about': {
      id: '/_portal/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PortalAboutRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/city-admins': {
      id: '/_portal/city-admins'
      path: '/city-admins'
      fullPath: '/city-admins'
      preLoaderRoute: typeof PortalCityAdminsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/contact': {
      id: '/_portal/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PortalContactRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/directory': {
      id: '/_portal/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof PortalDirectoryRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/events': {
      id: '/_portal/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof PortalEventsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/publications': {
      id: '/_portal/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PortalPublicationsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/vacancies': {
      id: '/_portal/vacancies'
      path: '/vacancies'
      fullPath: '/vacancies'
      preLoaderRoute: typeof PortalVacanciesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/admin/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/backgrounds': {
      id: '/admin/backgrounds'
      path: '/admin/backgrounds'
      fullPath: '/admin/backgrounds'
      preLoaderRoute: typeof AdminBackgroundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/city-admins': {
      id: '/admin/city-admins'
      path: '/admin/city-admins'
      fullPath: '/admin/city-admins'
      preLoaderRoute: typeof AdminCityAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/directory': {
      id: '/admin/directory'
      path: '/admin/directory'
      fullPath: '/admin/directory'
      preLoaderRoute: typeof AdminDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/admin/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/admin/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/job-applications': {
      id: '/admin/job-applications'
      path: '/admin/job-applications'
      fullPath: '/admin/job-applications'
      preLoaderRoute: typeof AdminJobApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/multimedia': {
      id: '/admin/multimedia'
      path: '/admin/multimedia'
      fullPath: '/admin/multimedia'
      preLoaderRoute: typeof AdminMultimediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/admin/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/portfolio': {
      id: '/admin/portfolio'
      path: '/admin/portfolio'
      fullPath: '/admin/portfolio'
      preLoaderRoute: typeof AdminPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/publications': {
      id: '/admin/publications'
      path: '/admin/publications'
      fullPath: '/admin/publications'
      preLoaderRoute: typeof AdminPublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/register': {
      id: '/admin/register'
      path: '/admin/register'
      fullPath: '/admin/register'
      preLoaderRoute: typeof AdminRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenders': {
      id: '/admin/tenders'
      path: '/admin/tenders'
      fullPath: '/admin/tenders'
      preLoaderRoute: typeof AdminTendersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vacancies': {
      id: '/admin/vacancies'
      path: '/admin/vacancies'
      fullPath: '/admin/vacancies'
      preLoaderRoute: typeof AdminVacanciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-reset/$token': {
      id: '/password-reset/$token'
      path: '/password-reset/$token'
      fullPath: '/password-reset/$token'
      preLoaderRoute: typeof PasswordResetTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/directory/': {
      id: '/_portal/directory/'
      path: '/'
      fullPath: '/directory/'
      preLoaderRoute: typeof PortalDirectoryIndexRouteImport
      parentRoute: typeof PortalDirectoryRoute
    }
    '/_portal/directory/$directorateId': {
      id: '/_portal/directory/$directorateId'
      path: '/$directorateId'
      fullPath: '/directory/$directorateId'
      preLoaderRoute: typeof PortalDirectoryDirectorateIdRouteImport
      parentRoute: typeof PortalDirectoryRoute
    }
    '/_portal/events/': {
      id: '/_portal/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof PortalEventsIndexRouteImport
      parentRoute: typeof PortalEventsRoute
    }
    '/_portal/events/$id': {
      id: '/_portal/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof PortalEventsIdRouteImport
      parentRoute: typeof PortalEventsRoute
    }
    '/_portal/multimedia/images': {
      id: '/_portal/multimedia/images'
      path: '/multimedia/images'
      fullPath: '/multimedia/images'
      preLoaderRoute: typeof PortalMultimediaImagesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/multimedia/videos': {
      id: '/_portal/multimedia/videos'
      path: '/multimedia/videos'
      fullPath: '/multimedia/videos'
      preLoaderRoute: typeof PortalMultimediaVideosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/news/': {
      id: '/_portal/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof PortalNewsIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/news/$id': {
      id: '/_portal/news/$id'
      path: '/news/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof PortalNewsIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/tenders/': {
      id: '/_portal/tenders/'
      path: '/tenders'
      fullPath: '/tenders/'
      preLoaderRoute: typeof PortalTendersIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/tenders/$id': {
      id: '/_portal/tenders/$id'
      path: '/tenders/$id'
      fullPath: '/tenders/$id'
      preLoaderRoute: typeof PortalTendersIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/vacancies/$vacancyId': {
      id: '/_portal/vacancies/$vacancyId'
      path: '/$vacancyId'
      fullPath: '/vacancies/$vacancyId'
      preLoaderRoute: typeof PortalVacanciesVacancyIdRouteImport
      parentRoute: typeof PortalVacanciesRoute
    }
    '/_portal/multimedia/images/': {
      id: '/_portal/multimedia/images/'
      path: '/'
      fullPath: '/multimedia/images/'
      preLoaderRoute: typeof PortalMultimediaImagesIndexRouteImport
      parentRoute: typeof PortalMultimediaImagesRoute
    }
    '/_portal/multimedia/images/$id': {
      id: '/_portal/multimedia/images/$id'
      path: '/$id'
      fullPath: '/multimedia/images/$id'
      preLoaderRoute: typeof PortalMultimediaImagesIdRouteImport
      parentRoute: typeof PortalMultimediaImagesRoute
    }
    '/_portal/multimedia/videos/': {
      id: '/_portal/multimedia/videos/'
      path: '/'
      fullPath: '/multimedia/videos/'
      preLoaderRoute: typeof PortalMultimediaVideosIndexRouteImport
      parentRoute: typeof PortalMultimediaVideosRoute
    }
    '/_portal/multimedia/videos/$id': {
      id: '/_portal/multimedia/videos/$id'
      path: '/$id'
      fullPath: '/multimedia/videos/$id'
      preLoaderRoute: typeof PortalMultimediaVideosIdRouteImport
      parentRoute: typeof PortalMultimediaVideosRoute
    }
    '/_portal/vacancies/$vacancyId/apply': {
      id: '/_portal/vacancies/$vacancyId/apply'
      path: '/apply'
      fullPath: '/vacancies/$vacancyId/apply'
      preLoaderRoute: typeof PortalVacanciesVacancyIdApplyRouteImport
      parentRoute: typeof PortalVacanciesVacancyIdRoute
    }
  }
}

interface PortalDirectoryRouteChildren {
  PortalDirectoryDirectorateIdRoute: typeof PortalDirectoryDirectorateIdRoute
  PortalDirectoryIndexRoute: typeof PortalDirectoryIndexRoute
}

const PortalDirectoryRouteChildren: PortalDirectoryRouteChildren = {
  PortalDirectoryDirectorateIdRoute: PortalDirectoryDirectorateIdRoute,
  PortalDirectoryIndexRoute: PortalDirectoryIndexRoute,
}

const PortalDirectoryRouteWithChildren = PortalDirectoryRoute._addFileChildren(
  PortalDirectoryRouteChildren,
)

interface PortalEventsRouteChildren {
  PortalEventsIdRoute: typeof PortalEventsIdRoute
  PortalEventsIndexRoute: typeof PortalEventsIndexRoute
}

const PortalEventsRouteChildren: PortalEventsRouteChildren = {
  PortalEventsIdRoute: PortalEventsIdRoute,
  PortalEventsIndexRoute: PortalEventsIndexRoute,
}

const PortalEventsRouteWithChildren = PortalEventsRoute._addFileChildren(
  PortalEventsRouteChildren,
)

interface PortalVacanciesVacancyIdRouteChildren {
  PortalVacanciesVacancyIdApplyRoute: typeof PortalVacanciesVacancyIdApplyRoute
}

const PortalVacanciesVacancyIdRouteChildren: PortalVacanciesVacancyIdRouteChildren =
  {
    PortalVacanciesVacancyIdApplyRoute: PortalVacanciesVacancyIdApplyRoute,
  }

const PortalVacanciesVacancyIdRouteWithChildren =
  PortalVacanciesVacancyIdRoute._addFileChildren(
    PortalVacanciesVacancyIdRouteChildren,
  )

interface PortalVacanciesRouteChildren {
  PortalVacanciesVacancyIdRoute: typeof PortalVacanciesVacancyIdRouteWithChildren
}

const PortalVacanciesRouteChildren: PortalVacanciesRouteChildren = {
  PortalVacanciesVacancyIdRoute: PortalVacanciesVacancyIdRouteWithChildren,
}

const PortalVacanciesRouteWithChildren = PortalVacanciesRoute._addFileChildren(
  PortalVacanciesRouteChildren,
)

interface PortalMultimediaImagesRouteChildren {
  PortalMultimediaImagesIdRoute: typeof PortalMultimediaImagesIdRoute
  PortalMultimediaImagesIndexRoute: typeof PortalMultimediaImagesIndexRoute
}

const PortalMultimediaImagesRouteChildren: PortalMultimediaImagesRouteChildren =
  {
    PortalMultimediaImagesIdRoute: PortalMultimediaImagesIdRoute,
    PortalMultimediaImagesIndexRoute: PortalMultimediaImagesIndexRoute,
  }

const PortalMultimediaImagesRouteWithChildren =
  PortalMultimediaImagesRoute._addFileChildren(
    PortalMultimediaImagesRouteChildren,
  )

interface PortalMultimediaVideosRouteChildren {
  PortalMultimediaVideosIdRoute: typeof PortalMultimediaVideosIdRoute
  PortalMultimediaVideosIndexRoute: typeof PortalMultimediaVideosIndexRoute
}

const PortalMultimediaVideosRouteChildren: PortalMultimediaVideosRouteChildren =
  {
    PortalMultimediaVideosIdRoute: PortalMultimediaVideosIdRoute,
    PortalMultimediaVideosIndexRoute: PortalMultimediaVideosIndexRoute,
  }

const PortalMultimediaVideosRouteWithChildren =
  PortalMultimediaVideosRoute._addFileChildren(
    PortalMultimediaVideosRouteChildren,
  )

interface PortalRouteChildren {
  PortalAboutRoute: typeof PortalAboutRoute
  PortalCityAdminsRoute: typeof PortalCityAdminsRoute
  PortalContactRoute: typeof PortalContactRoute
  PortalDirectoryRoute: typeof PortalDirectoryRouteWithChildren
  PortalEventsRoute: typeof PortalEventsRouteWithChildren
  PortalPublicationsRoute: typeof PortalPublicationsRoute
  PortalVacanciesRoute: typeof PortalVacanciesRouteWithChildren
  PortalIndexRoute: typeof PortalIndexRoute
  PortalMultimediaImagesRoute: typeof PortalMultimediaImagesRouteWithChildren
  PortalMultimediaVideosRoute: typeof PortalMultimediaVideosRouteWithChildren
  PortalNewsIdRoute: typeof PortalNewsIdRoute
  PortalTendersIdRoute: typeof PortalTendersIdRoute
  PortalNewsIndexRoute: typeof PortalNewsIndexRoute
  PortalTendersIndexRoute: typeof PortalTendersIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAboutRoute: PortalAboutRoute,
  PortalCityAdminsRoute: PortalCityAdminsRoute,
  PortalContactRoute: PortalContactRoute,
  PortalDirectoryRoute: PortalDirectoryRouteWithChildren,
  PortalEventsRoute: PortalEventsRouteWithChildren,
  PortalPublicationsRoute: PortalPublicationsRoute,
  PortalVacanciesRoute: PortalVacanciesRouteWithChildren,
  PortalIndexRoute: PortalIndexRoute,
  PortalMultimediaImagesRoute: PortalMultimediaImagesRouteWithChildren,
  PortalMultimediaVideosRoute: PortalMultimediaVideosRouteWithChildren,
  PortalNewsIdRoute: PortalNewsIdRoute,
  PortalTendersIdRoute: PortalTendersIdRoute,
  PortalNewsIndexRoute: PortalNewsIndexRoute,
  PortalTendersIndexRoute: PortalTendersIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PortalRoute: PortalRouteWithChildren,
  AdminAccountsRoute: AdminAccountsRoute,
  AdminActivityRoute: AdminActivityRoute,
  AdminBackgroundsRoute: AdminBackgroundsRoute,
  AdminCityAdminsRoute: AdminCityAdminsRoute,
  AdminDirectoryRoute: AdminDirectoryRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminJobApplicationsRoute: AdminJobApplicationsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminMultimediaRoute: AdminMultimediaRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPortfolioRoute: AdminPortfolioRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminPublicationsRoute: AdminPublicationsRoute,
  AdminRegisterRoute: AdminRegisterRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTendersRoute: AdminTendersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVacanciesRoute: AdminVacanciesRoute,
  PasswordResetTokenRoute: PasswordResetTokenRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
